"""create tables

Revision ID: 82be6edcc25b
Revises: 7d9fe9bcb581
Create Date: 2023-03-16 09:20:27.574853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82be6edcc25b'
down_revision = '7d9fe9bcb581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
